export const propertyData = [
  {
    address: '45 Victoria Street, Manchester M1 3GA',
    amenities: [
      'Kitchen',
      'Security',
      'Balcony',
      'Gym',
      'Parking',
      'Pet-Friendly',
      'Dishwasher',
    ],
    bathrooms: 2,
    bedrooms: 2,
    deposit: 2800,
    featured: true,
    furnished: true,
    garden: false,
    imgURLS: [],
    listType: 'rent',
    location: 'Manchester M1',
    monthly: '2400',
    nightly: '',
    offer: true,
    parking: true,
    propName: '2 bed modern apartment to rent',
    propertyDesc:
      'Stunning two bedroom apartment in the heart of Manchester city centre. Features modern kitchen, spacious living area, two bathrooms, and excellent transport links. Close to shopping districts and nightlife. Perfect for professionals or students.',
    propertyID: 'PROP001Manchester2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'Apartment',
    reactions: {
      heart: 2,
      laugh: 0,
      smile: 1,
      surprised: 0,
      thumbsUp: 3,
    },
    receptions: 1,
    sqrFt: 950,
    tags: ['manchester', 'city centre', 'modern'],
    views: 124,
    weekly: '600',
  },
  {
    address: '12 Park Lane, Birmingham B15 2TY',
    amenities: [
      'Kitchen',
      'Security',
      'Swimming Pool',
      'Gym',
      'Parking',
      'Concierge',
    ],
    bathrooms: 1,
    bedrooms: 1,
    deposit: 2200,
    featured: false,
    furnished: true,
    garden: false,
    imgURLS: [],
    listType: 'rent',
    location: 'Birmingham B15',
    monthly: '1800',
    nightly: '',
    offer: false,
    parking: true,
    propName: 'Luxury 1 bed flat with pool access',
    propertyDesc:
      'Elegant one bedroom flat in prestigious development with swimming pool and gym facilities. High-end finishes throughout, open plan living, and 24-hour concierge service. Located in vibrant Edgbaston area.',
    propertyID: 'PROP002Birmingham2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'Apartment',
    reactions: {
      heart: 5,
      laugh: 0,
      smile: 2,
      surprised: 1,
      thumbsUp: 4,
    },
    receptions: 1,
    sqrFt: 750,
    tags: ['birmingham', 'luxury', 'pool'],
    views: 89,
    weekly: '450',
  },
  {
    address: '78 Princes Street, Edinburgh EH2 2ER',
    amenities: [
      'Kitchen',
      'Security',
      'Balcony',
      'Pet-Friendly',
      'Dishwasher',
      'Fireplace',
    ],
    bathrooms: 3,
    bedrooms: 3,
    deposit: 4200,
    featured: true,
    furnished: false,
    garden: true,
    imgURLS: [],
    listType: 'rent',
    location: 'Edinburgh EH2',
    monthly: '3500',
    nightly: '',
    offer: true,
    parking: false,
    propName: '3 bed Victorian townhouse',
    propertyDesc:
      'Beautiful Victorian townhouse on famous Princes Street. Three spacious bedrooms, period features, private garden, and stunning views of Edinburgh Castle. Unfurnished to allow personal touches. Perfect for families.',
    propertyID: 'PROP003Edinburgh2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'House',
    reactions: {
      heart: 8,
      laugh: 0,
      smile: 3,
      surprised: 2,
      thumbsUp: 6,
    },
    receptions: 2,
    sqrFt: 1650,
    tags: ['edinburgh', 'victorian', 'castle view'],
    views: 156,
    weekly: '875',
  },
  {
    address: '23 Queens Road, Bristol BS8 1QE',
    amenities: [
      'Kitchen',
      'Security',
      'Parking',
      'Garden Access',
      'Dishwasher',
    ],
    bathrooms: 1,
    bedrooms: 2,
    deposit: 2600,
    featured: false,
    furnished: true,
    garden: true,
    imgURLS: [],
    listType: 'rent',
    location: 'Bristol BS8',
    monthly: '2100',
    nightly: '',
    offer: false,
    parking: true,
    propName: '2 bed garden flat in Clifton',
    propertyDesc:
      'Charming two bedroom ground floor flat in sought-after Clifton area. Features access to communal gardens, modern kitchen, and excellent transport links to city centre. Close to Clifton Suspension Bridge and local amenities.',
    propertyID: 'PROP004Bristol2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'Apartment',
    reactions: {
      heart: 3,
      laugh: 0,
      smile: 1,
      surprised: 0,
      thumbsUp: 2,
    },
    receptions: 1,
    sqrFt: 850,
    tags: ['bristol', 'clifton', 'garden'],
    views: 67,
    weekly: '525',
  },
  {
    address: '156 High Street, Leeds LS1 4HY',
    amenities: [
      'Kitchen',
      'Security',
      'Gym',
      'Parking',
      'Pet-Friendly',
      'Balcony',
      'Concierge',
    ],
    bathrooms: 2,
    bedrooms: 2,
    deposit: 3000,
    featured: true,
    furnished: true,
    garden: false,
    imgURLS: [],
    listType: 'rent',
    location: 'Leeds LS1',
    monthly: '2500',
    nightly: '',
    offer: true,
    parking: true,
    propName: '2 bed penthouse apartment',
    propertyDesc:
      'Stunning penthouse apartment with panoramic city views. Two double bedrooms, two bathrooms, spacious living area with balcony, and access to building gym and concierge services. Prime city centre location.',
    propertyID: 'PROP005Leeds2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'Apartment',
    reactions: {
      heart: 7,
      laugh: 0,
      smile: 4,
      surprised: 1,
      thumbsUp: 5,
    },
    receptions: 1,
    sqrFt: 1100,
    tags: ['leeds', 'penthouse', 'city views'],
    views: 203,
    weekly: '625',
  },
  {
    address: '89 Cathedral Street, Glasgow G1 2NR',
    amenities: ['Kitchen', 'Security', 'Parking', 'Dishwasher', 'Storage'],
    bathrooms: 1,
    bedrooms: 1,
    deposit: 1800,
    featured: false,
    furnished: true,
    garden: false,
    imgURLS: [],
    listType: 'rent',
    location: 'Glasgow G1',
    monthly: '1500',
    nightly: '',
    offer: false,
    parking: true,
    propName: '1 bed city centre studio',
    propertyDesc:
      'Compact and modern studio apartment in Glasgow city centre. Perfect for young professionals, featuring efficient layout, modern kitchen, and secure parking. Walking distance to shops, restaurants, and transport hubs.',
    propertyID: 'PROP006Glasgow2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'Apartment',
    reactions: {
      heart: 1,
      laugh: 0,
      smile: 0,
      surprised: 0,
      thumbsUp: 1,
    },
    receptions: 1,
    sqrFt: 450,
    tags: ['glasgow', 'studio', 'compact'],
    views: 45,
    weekly: '375',
  },
  {
    address: '34 Royal Crescent, Bath BA1 2LR',
    amenities: [
      'Kitchen',
      'Security',
      'Garden Access',
      'Fireplace',
      'Period Features',
      'Parking',
    ],
    bathrooms: 2,
    bedrooms: 3,
    deposit: 5000,
    featured: true,
    furnished: false,
    garden: true,
    imgURLS: [],
    listType: 'rent',
    location: 'Bath BA1',
    monthly: '4200',
    nightly: '',
    offer: false,
    parking: true,
    propName: '3 bed Georgian house',
    propertyDesc:
      'Magnificent Georgian house in historic Royal Crescent. Three large bedrooms, original period features, private garden access, and parking space. Unfurnished property with high ceilings and elegant proportions throughout.',
    propertyID: 'PROP007Bath2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'House',
    reactions: {
      heart: 12,
      laugh: 0,
      smile: 6,
      surprised: 4,
      thumbsUp: 9,
    },
    receptions: 3,
    sqrFt: 2100,
    tags: ['bath', 'georgian', 'historic'],
    views: 287,
    weekly: '1050',
  },
  {
    address: '67 Northgate Street, Canterbury CT1 1BA',
    amenities: [
      'Kitchen',
      'Security',
      'Pet-Friendly',
      'Garden Access',
      'Dishwasher',
    ],
    bathrooms: 1,
    bedrooms: 2,
    deposit: 2400,
    featured: false,
    furnished: true,
    garden: true,
    imgURLS: [],
    listType: 'rent',
    location: 'Canterbury CT1',
    monthly: '1900',
    nightly: '',
    offer: true,
    parking: false,
    propName: '2 bed cottage near cathedral',
    propertyDesc:
      'Charming two bedroom cottage in historic Canterbury, just minutes from the famous cathedral. Features traditional beams, modern kitchen, small garden, and pet-friendly policy. Perfect for those seeking character and history.',
    propertyID: 'PROP008Canterbury2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'House',
    reactions: {
      heart: 4,
      laugh: 0,
      smile: 2,
      surprised: 1,
      thumbsUp: 3,
    },
    receptions: 1,
    sqrFt: 750,
    tags: ['canterbury', 'cottage', 'historic'],
    views: 92,
    weekly: '475',
  },
  {
    address: '15 Waterfront Way, Liverpool L3 4DB',
    amenities: [
      'Kitchen',
      'Security',
      'Swimming Pool',
      'Balcony',
      'Gym',
      'Parking',
      'Concierge',
    ],
    bathrooms: 2,
    bedrooms: 2,
    deposit: 3200,
    featured: true,
    furnished: true,
    garden: false,
    imgURLS: [],
    listType: 'rent',
    location: 'Liverpool L3',
    monthly: '2700',
    nightly: '',
    offer: true,
    parking: true,
    propName: '2 bed waterfront apartment',
    propertyDesc:
      "Luxury two bedroom apartment with stunning waterfront views of Liverpool's historic docks. Modern development with swimming pool, gym, and 24-hour concierge. Balcony overlooking the Mersey River.",
    propertyID: 'PROP009Liverpool2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'Apartment',
    reactions: {
      heart: 9,
      laugh: 0,
      smile: 5,
      surprised: 2,
      thumbsUp: 7,
    },
    receptions: 1,
    sqrFt: 980,
    tags: ['liverpool', 'waterfront', 'luxury'],
    views: 178,
    weekly: '675',
  },
  {
    address: '42 King Street, Newcastle NE1 3UH',
    amenities: [
      'Kitchen',
      'Security',
      'Parking',
      'Pet-Friendly',
      'Dishwasher',
      'Storage',
    ],
    bathrooms: 1,
    bedrooms: 1,
    deposit: 2000,
    featured: false,
    furnished: true,
    garden: false,
    imgURLS: [],
    listType: 'rent',
    location: 'Newcastle NE1',
    monthly: '1600',
    nightly: '',
    offer: false,
    parking: true,
    propName: '1 bed loft apartment',
    propertyDesc:
      'Contemporary loft-style apartment in Newcastle city centre. Features exposed brick walls, high ceilings, modern kitchen, and secure parking. Close to universities, nightlife, and transport links. Great for students or young professionals.',
    propertyID: 'PROP010Newcastle2024',
    propertyOwner: 'eDCQqdp7NVdvjYVEKu9rmi7tzrS2',
    propertyType: 'Apartment',
    reactions: {
      heart: 2,
      laugh: 0,
      smile: 1,
      surprised: 0,
      thumbsUp: 2,
    },
    receptions: 1,
    sqrFt: 650,
    tags: ['newcastle', 'loft', 'student friendly'],
    views: 78,
    weekly: '400',
  },
]
